---
- name: Uninstall Jenkins
  hosts: localhost
  become: true
  tasks:
    - name: Stop Jenkins service
      systemd:
        name: jenkins
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Remove Jenkins package
      apt:
        name: jenkins
        state: absent

    - name: Remove Jenkins repository from sources.list
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: absent

    - name: Remove Jenkins apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 9B7D32F2D50582E6
        state: absent

    - name: Clean up apt cache
      apt:
        autoclean: yes
