---
- name: Install and configure Jenkins
  hosts: localhost
  become: true
  vars:
    jenkins_port: 8080
  tasks:
    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: present

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - openjdk-17-jre

    - name: Check Java version
      command: java -version
      register: java_version_output

    - debug:
        msg: "{{ java_version_output.stdout }}"

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Configure firewall for Jenkins
      firewalld:
        service: jenkins
        immediate: yes
        permanent: yes
        state: enabled
      ignore_errors: yes

    - name: Configure firewall for Jenkins
      ufw:
        rule: allow
        port: 8080
        proto: tcp
      ignore_errors: yes

    - name: Enable UFW
      ufw:
        state: enabled
      ignore_errors: yes
